apiVersion: v1	
kind: Service	
metadata:	
  name: studentsurveyapp	
spec:	
  ports:	
  - name: http
    port: 80	
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
  type: NodePort
  selector:	
    app: studentsurveyapp
