apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: studentsurveyapp
  name: studentsurveyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentsurveyapp
  template:
    metadata:
      labels:
        app: studentsurveyapp
    spec:
      containers:
      - image: cparupal/studentsurveyapp:0.4
        imagePullPolicy: Always
        name: studentsurveyapp
        ports:
        - containerPort: 80
          name: ssapp-port
          protocol: TCP
          
--- 
kind: Service 
apiVersion: v1 
metadata: 
  name: studentsurveyapp-service 
spec: 
  selector: 
    app: studentsurveyapp 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80
  type: NodePort 
