pipeline {
  agent any
  environment {
    DOCKERHUB_PASS = credentials('docker-pass')
  }
  stages {
    stage ("Building the web app into a docker image"){
      steps {
        script {
          checkout scm
          sh "docker login -u cparupal -p $DOCKERHUB_PASS_PSW"
          sh "docker build -t cparupal/studentsurveyapp:${env.BUILD_ID} surveyapp"
          
        }
      }
    }
    
    stage("Pushing Image to Dockerhub"){
      steps{
        script{
          sh "docker push cparupal/studentsurveyapp:${env.BUILD_ID}"
        }
      }
    }
    
    stage("Updating deployment.yaml file with new Build"){
      steps{
        script{
          sh 'rm -rf SWE645HW3_argoCD'
          sh "git config --global user.email 'chetana.p98@gmail.com'"
          sh 'git remote set-url origin git@github.com:cparupal/SWE645HW3_argoCD.git'
          sh 'git clone git@github.com:cparupal/SWE645HW3_argoCD.git'
          sh 'pwd'
          sh 'ls'
          dir('SWE645HW3_argoCD/surveyapp'){
            sh "git config --global user.email 'chetana.p98@gmail.com'"
            sh 'git checkout main'
            sh 'git pull'
            sh 'pwd'
            sh 'ls'
            sh "sed -i 's/studentsurveyapp:.*/studentsurveyapp:${env.BUILD_ID}/' deployment.yaml"
            sh 'git add deployment.yaml'
            sh "git commit -m 'Uploading deployment.yaml with build image ${env.BUILD_ID}'"
            sh "git push"
          }
        }
      }
    }

  }
}
